GET http://localhost:3000

###
POST http://localhost:3000/lokasi
Content-Type: application/json

{
    "long" : "1200",
    "lat" : "120312",
    "tingker": 40,
    "token" : "onichanbaka"
}

### 
GET http://localhost:3000/lokasi

###
DELETE  http://localhost:3000/lokasi/64383c6f0a8b70def4072397