GET https://wild-rose-cod-hem.cyclic.app/

###
POST https://wild-rose-cod-hem.cyclic.app/lokasi
Content-Type: application/json

{
    "long" : "1200",
    "lat" : "120312",
    "tingker": 400,
    "token" : "onichanbaka"
}

### 
GET https://wild-rose-cod-hem.cyclic.app//lokasi

###
DELETE  https://wild-rose-cod-hem.cyclic.app//lokasi/64383c6f0a8b70def4072397